// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXtEePyitQdcBAJHFAI2Q1-WwklKZhvF4',
    appId: '1:349841041885:web:1f82ebc3f75f8823f26e34',
    messagingSenderId: '349841041885',
    projectId: 'mytikstore-cd9de',
    authDomain: 'mytikstore-cd9de.firebaseapp.com',
    storageBucket: 'mytikstore-cd9de.appspot.com',
    measurementId: 'G-P8K11DXL11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq0fAkHSAhYO8I__GV5Y7ba1VJ144rxgw',
    appId: '1:349841041885:android:14f7b08f8a8555c4f26e34',
    messagingSenderId: '349841041885',
    projectId: 'mytikstore-cd9de',
    storageBucket: 'mytikstore-cd9de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcy__tYmPEA4-6P1YSYIZ_09g_YFCnUT8',
    appId: '1:349841041885:ios:98e307c5cd57387af26e34',
    messagingSenderId: '349841041885',
    projectId: 'mytikstore-cd9de',
    storageBucket: 'mytikstore-cd9de.appspot.com',
    iosBundleId: 'com.example.tikstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcy__tYmPEA4-6P1YSYIZ_09g_YFCnUT8',
    appId: '1:349841041885:ios:c5a9c0526bfd7624f26e34',
    messagingSenderId: '349841041885',
    projectId: 'mytikstore-cd9de',
    storageBucket: 'mytikstore-cd9de.appspot.com',
    iosBundleId: 'com.example.tikstore.RunnerTests',
  );
}
